#!/usr/bin/env node
// Approval server for the workflow plan-gate's graph editor.
//
// Spawned DETACHED by the hook, which then exits immediately — the hook must never be the blocking
// wait, because a timed-out PreToolUse hook fails OPEN to the interactive prompt. This process
// outlives it, serves the editor, and on Approve does exactly what the `record` CLI does today.
// The agent's next retry re-enters the gate, finds the fingerprint, and proceeds.
//
// After Approve it does NOT exit: it enters run mode and keeps serving the same page read-only, so
// the tab that approved the plan becomes the live view of the run it started. Every POST answers
// 409 from that moment on — there is exactly one approval per session, before and after.
//
// Security: the nonce is generated by the hook and appears ONLY in the URL opened in the browser.
// Without it, a bare POST /approve would be easier for an agent to self-approve than today's named
// CLI command — a net regression. Loopback-bound, Origin-checked, single-use.
// The port file also carries a stateToken so a RETRY of the hook can reattach to this tab instead of
// opening another. The agent can read that file, so the token opens exactly one door: GET /state.
//
// ponytail: zero dependencies. Parsing and splicing happen in the browser (acorn from cdnjs), so
// this process only reads a file, writes a file, tails a few JSONL files, and shells out to the
// hook to record.

import { createServer } from 'node:http';
import { readFileSync, writeFileSync, copyFileSync, readdirSync, statSync, existsSync, openSync, readSync, closeSync } from 'node:fs';
import { readFile, readdir, stat } from 'node:fs/promises';
import { execFileSync, execFile } from 'node:child_process';
import { join, dirname, resolve, basename, isAbsolute } from 'node:path';
import { homedir } from 'node:os';
import { randomBytes } from 'node:crypto';
import { fileURLToPath } from 'node:url';
// Pure functions doing arithmetic on numbers this process already has in hand, plus a read of the
// small priors index the history daemon precomputes. The cost CACHE — the thing that walks 200 MB of
// transcripts — stays out of the gate process on purpose.
import { costOf, addEntry, priceOf, priorsFor } from './cost.mjs';
import { askJev, agentTypes } from './advise.mjs';

const [, , nonce, portFile, scriptPath, sessionArg, cwdArg] = process.argv;
// The calling session: its run directory is looked for there first. One path segment or nothing.
const SESSION = /^[\w-]+$/.test(sessionArg || '') ? sessionArg : null;
// The session's cwd, for <project>/.claude/agents in the agent-type catalog. Absent: user + built-ins.
const PROJECT = cwdArg && isAbsolute(cwdArg) ? cwdArg : null;
const HERE = dirname(fileURLToPath(import.meta.url));
const GATE = join(HERE, 'workflow-plan-gate.mjs');
const PROJECTS = join(homedir(), '.claude', 'projects');
const ADVICE_CACHE = join(homedir(), '.claude', 'workflow-gate', 'advice');
const IDLE_MS = 20 * 60 * 1000;         // before a decision: deny by default (outlives the hook's own wait)
const POLL_IDLE_MS = 5 * 60 * 1000;     // after approval: nobody is watching, stop serving
const LINGER_MS = 60 * 1000;            // after the run record lands: let the last poll land too
const HOOK_WAIT_MS = 5000;              // the hook polls /state every second; older means it stopped
// The page heartbeats /state every 5 s, but a hidden tab's timers drop to about once a minute
// (Chrome, after 5 min hidden). Above that, silence means the tab is gone.
const PAGE_ALIVE_MS = 90 * 1000;
const stateToken = randomBytes(16).toString('hex');
const startedAt = Date.now();

// Read-only routes stay open in run mode. Every POST is answered 409 once `decided` is set — the
// single-approval guarantee is that line, not the process exiting.
const LIVE_GETS = new Set(['/', '/script', '/run', '/live', '/state', '/priors']);

// `seen` = a human moved the mouse or typed on the page. The hook polls /state and waits for the
// decision only while someone is actually there: `open` launches the tab whether or not anyone is
// at the desk, so a page load alone proves nothing.
let decided = false, approved = false, seen = false, runMode = false, approvedAt = 0, lastPoll = 0, finishedAt = 0;
let lastHookPoll = 0, lastPagePoll = 0;
let CAP = null;                         // the human's spend cap in $, or null. Shown and alerted on by the page, enforced by nothing.
const die = (code) => { server.close(); server.closeAllConnections(); setTimeout(() => process.exit(code), 50).unref(); };

const server = createServer((req, res) => {
  const url = new URL(req.url, 'http://127.0.0.1');
  const send = (code, body, type = 'text/plain; charset=utf-8') => {
    res.writeHead(code, { 'content-type': type, 'cache-control': 'no-store' });
    res.end(body);
  };

  // Nonce first, before any routing. A local process must know it. The one exception is the
  // read-only state probe by stateToken: GET, /state, nothing else — it can never approve or cancel.
  const byToken = req.method === 'GET' && url.pathname === '/state' && url.searchParams.get('t') === stateToken;
  if (!byToken && url.searchParams.get('n') !== nonce) return send(403, 'bad nonce');
  // A cross-site POST would carry an Origin we don't own — and a POST from a script (curl, node)
  // carries none at all. Only the page this server itself served can approve, so Origin is
  // MANDATORY on POST: without this, a leaked nonce is one request away from self-approval.
  const origin = req.headers.origin;
  if (origin && !/^http:\/\/127\.0\.0\.1:\d+$/.test(origin)) return send(403, 'bad origin');
  if (req.method === 'POST' && !origin) return send(403, 'approval must come from the editor page');
  if (decided && !(runMode && req.method === 'GET' && LIVE_GETS.has(url.pathname)))
    return send(409, 'this approval session is already closed');

  try {
    if (url.pathname === '/' && req.method === 'GET') {
      // The history daemon's port file is an ORDINARY USER-WRITABLE FILE, and the agent this gate
      // exists to constrain can write it. Its contents are spliced into this page's <script>, three
      // lines from `const NONCE`, so an unvalidated nonce here is a self-approval path: close the
      // quote, run JS in the page's own origin, pass the Origin check, POST /approve. Both fields
      // are therefore checked against exactly what the daemon writes, and anything else is ignored.
      let history = '';
      try {
        const h = JSON.parse(readFileSync(join(homedir(), '.claude', 'workflow-gate-history-port'), 'utf8'));
        process.kill(h.pid, 0);                       // throws if that daemon is gone
        if (Number.isInteger(h.port) && h.port > 0 && h.port < 65536 && /^[0-9a-f]{32,64}$/.test(h.nonce))
          history = 'http://127.0.0.1:' + h.port + '/?n=' + h.nonce;
      } catch { /* no viewer running, or a port file we do not trust: no link */ }
      // Function replacements, never string ones: `$&`, `$\`` and `$'` in a replacement string are
      // substitution patterns, and `$'` alone would splice the rest of the document into the page.
      const html = readFileSync(join(HERE, 'graph-editor.html'), 'utf8')
        .replace('__NONCE__', () => nonce)
        .replace('__HISTORY_URL__', () => history)
        .replace('__SCRIPT_PATH__', () => JSON.stringify(scriptPath).slice(1, -1));
      return send(200, html, 'text/html; charset=utf-8');
    }

    // The script text, verbatim. The editor parses and splices it client-side.
    if (url.pathname === '/script' && req.method === 'GET') {
      return send(200, readFileSync(scriptPath, 'utf8'));
    }

    // The text last approved for this path, for the editor's diff — or null. The hook owns where it
    // lives and whether it is genuine (a matching approval in its state), so this only relays.
    if (url.pathname === '/approved' && req.method === 'GET') {
      execFile(process.execPath, [GATE, 'baseline', '--path', scriptPath], { encoding: 'utf8', timeout: 5000 },
        (err, out) => send(200, err ? 'null' : out.trim() || 'null', 'application/json; charset=utf-8'));
      return;
    }

    // The newest COMPLETED run of THIS script, from the run records Claude Code already writes.
    // Async, so a cold scan never stalls the hook's /state poll; the catch is here because a rejected
    // promise escapes the try around this handler and would take the server down mid-review.
    if (url.pathname === '/run' && req.method === 'GET') {
      lastRunOf(scriptPath).then((r) => send(200, JSON.stringify(r), 'application/json; charset=utf-8'),
        (e) => send(500, String(e.message)));
      return;
    }

    // What past runs of this workflow cost — numbers only, or null with no history. The name comes
    // from the file being approved (the gate's own regex), never from the page.
    if (url.pathname === '/priors' && req.method === 'GET') {
      let src = null; try { src = readFileSync(scriptPath, 'utf8'); } catch {}
      const name = src?.match(/name:\s*['"]([^'"]+)['"]/)?.[1];
      return send(200, JSON.stringify(name ? priorsFor(name, src) : null), 'application/json; charset=utf-8');
    }

    // What the hook waits on (by stateToken) and what the page heartbeats (by nonce). Read by a node
    // process, so no Origin — GET only. Each side's last poll tells the other one it is still there.
    if (url.pathname === '/state' && req.method === 'GET') {
      const now = Date.now();
      if (byToken) {
        lastHookPoll = now;
        if (!decided) idleTimer.refresh();   // a waiting hook keeps the deny-by-default clock fresh
      } else lastPagePoll = now;
      return send(200, JSON.stringify({ seen, decided, approved, since: startedAt,
        hookWaiting: lastHookPoll ? now - lastHookPoll < HOOK_WAIT_MS : null, hookLastPoll: lastHookPoll,
        pageAlive: !!lastPagePoll && now - lastPagePoll < PAGE_ALIVE_MS }), 'application/json; charset=utf-8');
    }
    if (url.pathname === '/seen' && req.method === 'POST') { seen = true; return send(200, 'ok'); }

    // The run this approval started, while it is still going.
    if (url.pathname === '/live' && req.method === 'GET') {
      lastPoll = Date.now();
      return send(200, JSON.stringify({ ...(runMode ? liveRun() : { running: false, agents: [] }), cap: CAP }),
        'application/json; charset=utf-8');
    }

    // Intent, model and agent-type routing on Jev. The editor posts the skeleton IT extracted (no
    // second parser here); the key stays in this process. POST, so the Origin check above applies:
    // only the page can trigger egress of mission text and agent-type descriptions. Advice only —
    // nothing here touches `decided`. A repeat of the exact payload (a retry, an undo) is served
    // from ADVICE_CACHE without calling Jev. The catalog is re-read per ask: an edited definition shows.
    if (url.pathname === '/advice' && req.method === 'POST') {
      if (!process.env.TYPESAFE_API_KEY) return send(200, JSON.stringify({ available: false }), 'application/json; charset=utf-8');
      let body = '';
      req.on('data', (c) => { body += c; if (body.length > 1e6) req.destroy(); });
      req.on('end', async () => {
        try {
          const skel = JSON.parse(body);
          if (!Array.isArray(skel.agents)) return send(400, 'no agents');
          const types = agentTypes(PROJECT);
          const advice = await askJev(skel, ADVICE_CACHE, types);
          // Per-token input price per tier, from the one price table, so the page can say what a
          // suggested tier is worth without keeping a second copy that drifts.
          const prices = Object.fromEntries(['haiku', 'sonnet', 'opus', 'fable'].map((t) => [t, priceOf(t)?.in ?? null]));
          // The catalog without descriptions: enough for the page to show the tools of a type already written.
          const catalog = types.map(({ name, tools, skills, source }) => ({ name, tools, skills, source }));
          send(200, JSON.stringify(advice ? { available: true, ...advice, prices, catalog } : { available: false }), 'application/json; charset=utf-8');
        } catch (e) { send(500, String(e.message)); }
      });
      return;
    }

    if (url.pathname === '/approve' && req.method === 'POST') {
      let body = '';
      req.on('data', (c) => { body += c; if (body.length > 8e6) req.destroy(); });
      req.on('end', () => {
        try {
          const { script, summary, match, cap } = JSON.parse(body);
          if (typeof script !== 'string' || !script.trim()) return send(400, 'empty script');
          // A typeof check, not `+cap`: coercing an object with string valueOf/toString keys throws,
          // and a throw here is "approval failed". Anything odd is simply no cap.
          CAP = typeof cap === 'number' && Number.isFinite(cap) && cap > 0 ? cap : null;
          decided = true; seen = true;
          // Back up first. This overwrites the user's file, and the browser is the only thing that
          // validated the content — if that check is ever wrong, the original must still exist.
          try { copyFileSync(scriptPath, scriptPath + '.gate-backup'); } catch {}
          // Write the edited script BEFORE recording: the fingerprint is computed from the file, so
          // recording first would approve the pre-edit content.
          writeFileSync(scriptPath, script);
          // The hook owns fingerprinting (content + its own version). Shelling out to it keeps one
          // source of truth instead of a copy that silently drifts on the next version bump.
          const out = execFileSync(process.execPath,
            [GATE, 'approve-path', '--path', scriptPath, '--summary', String(summary || 'approved in graph editor')],
            { encoding: 'utf8' });
          approved = true;                // only after the hook confirmed the fingerprint landed
          send(200, out.trim());
          enterRunMode(match);
        } catch (e) {
          send(500, 'approval failed, gate left active: ' + String(e.message));
          die(1);
        }
      });
      return;
    }

    // Closing the tab must NOT approve. This is the explicit-cancel path; the timeout below is the
    // implicit one. Both leave the gate active.
    if (url.pathname === '/cancel' && req.method === 'POST') {
      decided = true;
      send(200, 'cancelled — gate still active');
      return die(3);
    }

    send(404, 'no');
  } catch (e) {
    send(500, String(e.message));
  }
});

// The gate is decided; the only job left is showing the run. The 15-minute deny-by-default timer
// has done its work and must go, or it would kill the view mid-run.
function enterRunMode(match) {
  runMode = true;
  approvedAt = Date.now();
  lastPoll = Date.now();
  setMatchSpec(match);
  clearTimeout(idleTimer);
  setInterval(() => {
    if (finishedAt && Date.now() - finishedAt > LINGER_MS) return die(0);
    if (Date.now() - lastPoll > POLL_IDLE_MS) return die(0);   // tab closed, or never opened again
  }, 15000).unref();
}

// ~/.claude/projects/<proj>/<session>/workflows/wf_<id>.json carries the script that ran, the real
// agentCount, tokens, and one entry per launched agent (label, model, state, tokens, toolCalls).
// Match by path or by script content (line endings ignored). Once this server has watched a run to
// the end it reads THAT record, not whichever is newest. ponytail: otherwise a directory scan of a
// few hundred small JSON files, no index; cap at 400 records, newest first, 16 reads in flight,
// scanned once per server lifetime (the page asks once, at load).
const norm = (s) => String(s || '').replace(/\r\n/g, '\n').trim();
const ofScript = (r, path, mine) => (r.scriptPath && resolve(r.scriptPath) === resolve(path)) || (mine && norm(r.script) === mine);
function recordToRun(r) {
  const agents = (r.workflowProgress || []).filter((x) => x.type === 'workflow_agent').map((a) => ({
    label: a.label, phase: a.phaseTitle, model: a.model, state: a.state, tokens: a.tokens, toolCalls: a.toolCalls,
    durationMs: a.durationMs, resultPreview: String(a.resultPreview || '').slice(0, 400) }));
  return { runId: r.runId, status: r.status, timestamp: r.timestamp, agentCount: r.agentCount, totalTokens: r.totalTokens,
    totalToolCalls: r.totalToolCalls, durationMs: r.durationMs, defaultModel: r.defaultModel, agents };
}
let runScan = null;
async function lastRunOf(path) {
  const mine = await readFile(path, 'utf8').then(norm, () => null);
  if (finishedAt && runId && sessionDir) {
    const r = await readFile(join(sessionDir, 'workflows', runId + '.json'), 'utf8').then(JSON.parse).catch(() => null);
    if (r && ofScript(r, path, mine)) return recordToRun(r);
  }
  return runScan ||= scanRuns(path, mine);
}
const BATCH = 16;
const inBatches = async (xs, fn) => { const out = []; for (let i = 0; i < xs.length; i += BATCH) out.push(...await Promise.all(xs.slice(i, i + BATCH).map(fn))); return out; };
async function scanRuns(path, mine) {
  const lsa = (p) => readdir(p).catch(() => []);
  const dirs = (await inBatches(await lsa(PROJECTS), async (proj) => (await lsa(join(PROJECTS, proj))).map((s) => join(PROJECTS, proj, s, 'workflows')))).flat();
  const files = (await inBatches(dirs, async (d) => (await lsa(d)).filter((f) => /^wf_.*\.json$/.test(f)).map((f) => join(d, f)))).flat();
  const dated = (await inBatches(files, (f) => stat(f).then((st) => ({ f, t: st.mtimeMs }), () => null)))
    .filter(Boolean).sort((a, b) => b.t - a.t).slice(0, 400);
  for (let i = 0; i < dated.length; i += BATCH) {
    const rs = await Promise.all(dated.slice(i, i + BATCH).map(({ f }) => readFile(f, 'utf8').then(JSON.parse).catch(() => null)));
    const hit = rs.find((r) => r && ofScript(r, path, mine));
    if (hit) return recordToRun(hit);
  }
  return null;
}

// ---------------------------------------------------------------------------- live tail
// DURING a run Claude Code writes <session>/subagents/workflows/wf_<id>/ with journal.jsonl
// (started/result events keyed by agentId) and one agent-<id>.jsonl transcript per agent. Neither
// carries a label or a phase — only the prompt does, and the consolidated record that has labels,
// phases and token counts is written at completion, not before. Checked on the 21 recorded runs on
// the author's machine: there is no other live source.
//
// So the call site an agent belongs to is decided HERE, by searching its prompt for the literal
// chunks the browser extracted from each call site and handed over at approval time. The browser
// cannot do it: prompts run to 190 000 characters and the deciding chunk has been found as far in
// as 26 000, so no prefix small enough to ship every poll is big enough to match on. This way the
// prompt is read once, matched once, and dropped — only an id crosses the wire.
//
// ponytail: substring search over a few dozen needles, once per agent. Every file is read
// forward-only from a remembered byte offset, so a 30-agent run costs one stat plus the new bytes
// per poll, not 15 MB of re-reads. Ceiling: that state is in memory, so a restarted server would
// re-read from 0 — still correct, just slower.
const MAX_NODES = 200, MAX_CHUNKS = 2000, MAX_CHUNK = 4000;
let matchSpec = [];                        // [nodeId, [chunk, …]] pairs, bounded
let runDir = null, runId = null, sessionDir = null, runGuess = false;
const journal = { offset: 0 };
const liveAgents = new Map();              // agentId → facts accumulated across polls

// Whatever the page sends is data, not code: bound it hard before it becomes work done per agent.
function setMatchSpec(match) {
  matchSpec = [];
  if (!match || typeof match !== 'object') return;
  let budget = MAX_CHUNKS;
  for (const [id, chunks] of Object.entries(match).slice(0, MAX_NODES)) {
    if (!Array.isArray(chunks)) continue;
    const clean = chunks.filter((c) => typeof c === 'string' && c.length >= 24)
      .slice(0, budget).map((c) => c.slice(0, MAX_CHUNK));
    budget -= clean.length;
    if (clean.length) matchSpec.push([String(id), clean]);
    if (budget <= 0) break;
  }
}

// Longest matching chunk wins: a 300-character shared preamble must not outrank the one sentence
// that actually names this call site. Two sites CAN be indistinguishable — two calls to the same
// promptFor(x) helper differ only in what x resolves to at runtime — and then the longest match is a
// tie, not an answer. Measured on the 196 recorded agents with a known label: picking the first of a
// tie placed 7 of them on the wrong call site, silently. A tie is reported as a tie; the browser
// places it by arrival order among the tied sites and says in the panel that it did.
function nodeFor(prompt) {
  let best = 0, tied = [];
  for (const [id, chunks] of matchSpec) {
    let len = 0;
    for (const c of chunks) if (c.length > len && prompt.includes(c)) len = c.length;
    if (!len) continue;
    if (len > best) { best = len; tied = [id]; } else if (len === best) tied.push(id);
  }
  return { nodeId: tied.length === 1 ? tied[0] : null, matchLen: best, tied: tied.length > 1 ? tied : null };
}

function readLines(file, st, onLine) {
  let size; try { size = statSync(file).size; } catch { return; }
  if (size <= st.offset) return;
  let fd;
  try {
    fd = openSync(file, 'r');
    const buf = Buffer.allocUnsafe(size - st.offset);
    // A short read — the file truncated between stat and read — would otherwise decode uninitialised
    // heap as UTF-8 and scan it for a newline, desynchronising this agent's offset for good.
    const got = readSync(fd, buf, 0, buf.length, st.offset);
    if (!got) return;
    const text = buf.subarray(0, got).toString('utf8');
    const cut = text.lastIndexOf('\n');
    if (cut < 0) return;                                   // no complete line yet, wait for more
    st.offset += Buffer.byteLength(text.slice(0, cut + 1));
    for (const line of text.slice(0, cut).split('\n')) {
      const t = line.trim();
      if (!t) continue;
      let e; try { e = JSON.parse(t); } catch { continue; }
      onLine(e);
    }
  } catch { /* mid-write, or gone: the next poll retries from the same offset */ }
  finally { if (fd !== undefined) { try { closeSync(fd); } catch {} } }
}

// Which run directory is THIS approval's run. Looked for in the calling session first; everywhere
// only after SCOPE_MISSES polls find nothing verified there (a Workflow launched from a subagent can
// write under another session dir). A candidate is verified when one of its first agents' prompts
// matches a call site of the approved script, so a concurrent workflow cannot take the view. When
// nothing CAN be verified — no literal needles at all, or none matches after GUESS_AFTER polls — it
// falls back to newest-wins and says it guessed. A candidate with no prompt written yet stretches
// each of those waits threefold, never forever: a run that died before its first agent must not
// hold the view hostage.
// ponytail: the wide walk is synchronous, so once wide it runs every WIDE_EVERY polls and the
// session alone is checked in between; it stops for good once a directory is bound.
const SCOPE_MISSES = 5, GUESS_AFTER = 3, WIDE_EVERY = 10;
let wide = !SESSION, unverified = 0, widePolls = 0, rechecks = 0;
const notOurs = new Set();                 // guessed dirs whose finished record named another script
const ls = (p) => { try { return readdirSync(p); } catch { return []; } };
function candidates(full) {
  const out = [];
  for (const proj of ls(PROJECTS)) for (const sess of full ? ls(join(PROJECTS, proj)) : [SESSION]) {
    const base = join(PROJECTS, proj, sess, 'subagents', 'workflows');
    for (const d of ls(base)) {
      if (!/^wf_/.test(d)) continue;
      let t; try { t = statSync(join(base, d)).mtimeMs; } catch { continue; }
      if (t + 5000 < approvedAt || notOurs.has(join(base, d))) continue;   // predates this approval, or ruled out
      out.push({ t, dir: join(base, d), id: d, sess: join(PROJECTS, proj, sess) });
    }
  }
  return out.sort((a, b) => b.t - a.t);
}
// The prompt an agent was given: the first transcript line that carries one. null = no complete
// line yet; '' = complete lines, none with a prompt. ponytail: reads at most 1 MB; a longer first
// line reads as not written yet.
function firstPrompt(file) {
  let fd;
  try {
    fd = openSync(file, 'r');
    const buf = Buffer.allocUnsafe(1 << 20);
    const text = buf.subarray(0, readSync(fd, buf, 0, buf.length, 0)).toString('utf8');
    const cut = text.lastIndexOf('\n');
    if (cut < 0) return null;
    for (const line of text.slice(0, cut).split('\n')) {
      let e; try { e = JSON.parse(line); } catch { continue; }
      const p = promptOf(e);
      if (p) return p;
    }
    return '';
  } catch { return null; }
  finally { if (fd !== undefined) { try { closeSync(fd); } catch {} } }
}
// 'match' | 'none' (prompts in hand, none of ours) | 'pending' (no prompt written yet)
function verdictOf(dir) {
  let seenOne = false;
  for (const f of ls(dir).filter((f) => /^agent-.+\.jsonl$/.test(f)).slice(0, 5)) {
    const p = firstPrompt(join(dir, f));
    if (p === null) continue;
    seenOne = true;
    if (p && nodeFor(p).matchLen) return 'match';
  }
  return seenOne ? 'none' : 'pending';
}
function findRunDir() {
  const full = !SESSION || (wide && widePolls++ % WIDE_EVERY === 0);
  const all = candidates(full);
  const mineFirst = all.find((c) => basename(c.sess) === SESSION) || all[0];
  if (all.length && !matchSpec.length) return { ...mineFirst, guess: true };
  let pending = false;
  for (const c of all) {
    const v = verdictOf(c.dir);
    if (v === 'match') return c;
    if (v === 'pending') pending = true;
  }
  if (wide && !full) return null;                    // between wide walks: only a verified hit binds
  unverified++;
  if (!wide) { if (unverified >= SCOPE_MISSES * (pending ? 3 : 1)) { wide = true; unverified = 0; } return null; }
  if (all.length && unverified >= GUESS_AFTER * (pending ? 3 : 1)) return { ...mineFirst, guess: true };
  return null;
}

function promptOf(e) {
  const c = e.message?.content;
  return typeof c === 'string' ? c
    : (e.type === 'user' && Array.isArray(c)) ? c.filter((b) => b.type === 'text').map((b) => b.text || '').join('\n') : '';
}

function liveAgentOf(id) {
  let a = liveAgents.get(id);
  if (!a) liveAgents.set(id, a = { agentId: id, offset: 0, matched: false, nodeId: null, matchLen: 0, tied: null,
    startedAt: null, lastAt: null, lines: 0, toolCalls: 0, lastTool: null, done: false, failed: false, resultPreview: '',
    model: null, cost: null, usage: { in: 0, cw: 0, cr: 0, out: 0, turns: 0 }, seen: new Map() });
  return a;
}

function bind(f) {
  runDir = f?.dir ?? null; runId = f?.id ?? null; sessionDir = f?.sess ?? null; runGuess = !!f?.guess;
  liveAgents.clear(); journal.offset = 0;
}
const NOT_STARTED = { running: true, started: false, finished: false, agents: [] };
function liveRun() {
  // A guess holds the view only until the verified run shows up — e.g. the approval landed after
  // Claude stopped waiting, and a newer, unrelated workflow was bound while nobody had retried yet.
  // ponytail: re-verifying is the same walk as the search, so it runs every WIDE_EVERY polls.
  if (runDir && runGuess && matchSpec.length && ++rechecks % WIDE_EVERY === 0) {
    const v = findRunDir();
    if (v && !v.guess) bind(v);
  }
  if (!runDir) {
    const found = findRunDir();
    if (!found) return NOT_STARTED;
    bind(found);
  }

  // The agent list comes from the transcript files, never from the journal: a file exists because
  // its agent started, whereas a journal flushed at the end (rather than appended, as observed)
  // would leave the view empty for the whole run.
  try { for (const f of readdirSync(runDir)) { const m = /^agent-(.+)\.jsonl$/.exec(f); if (m) liveAgentOf(m[1]); } } catch {}

  readLines(join(runDir, 'journal.jsonl'), journal, (e) => {
    if (!e.agentId) return;
    const a = liveAgentOf(e.agentId);
    if (e.type === 'result') {
      a.done = true;
      const r = e.result;
      a.resultPreview = String(typeof r === 'string' ? r : JSON.stringify(r ?? '')).slice(0, 400);
      if (r && typeof r === 'object' && (r.error || r.failed)) a.failed = true;
    }
  });

  for (const [id, a] of liveAgents) {
    readLines(join(runDir, 'agent-' + id + '.jsonl'), a, (e) => {
      a.lines++;
      if (e.timestamp) { a.lastAt = e.timestamp; a.startedAt = a.startedAt || e.timestamp; }
      const c = e.message?.content;
      // The first user message IS the prompt the agent was given — verified against every recorded
      // run here. Match on it once, then let it go: keeping 190 KB per agent buys nothing.
      const text = a.matched ? '' : promptOf(e);
      if (text) { a.matched = true; Object.assign(a, nodeFor(text)); }
      if (Array.isArray(c)) for (const b of c) if (b.type === 'tool_use') { a.toolCalls++; a.lastTool = b.name; }
      // Spend, in the same forward-only pass that is already reading these lines. The record that
      // would tell you this arrives at completion; by then the money is gone. Deduped by message.id
      // in cost.mjs. No '"usage"' pre-parse reject here: this pass needs every line for its counts.
      if (addEntry(a.usage, e, a.seen)) a.model = a.model || a.usage.model || null;
    });
  }

  let cost = 0, unpriced = false;
  for (const a of liveAgents.values()) {
    a.cost = costOf(a.model, a.usage);
    if (a.cost === null) { if (a.usage.turns) unpriced = true; } else cost += a.cost;
  }
  const record = runId && sessionDir && join(sessionDir, 'workflows', runId + '.json');
  const finished = !!(record && existsSync(record));
  // A guessed run that finished as ANOTHER script was never ours: rule it out and keep looking, or
  // its finish would end this view before the approved run starts. Guesses only — a verified run
  // whose record lacks script and scriptPath must still be able to finish.
  if (finished && runGuess) {
    let r = null, mine = null;
    try { r = JSON.parse(readFileSync(record, 'utf8')); mine = norm(readFileSync(scriptPath, 'utf8')); } catch {}
    if (r && !ofScript(r, scriptPath, mine)) { notOurs.add(runDir); bind(null); return NOT_STARTED; }
  }
  if (finished && !finishedAt) finishedAt = Date.now();
  return {
    running: true, started: true, finished, runId, cost, unpriced,
    // Say how this run was found when it was not by its own prompts, or not in the calling session.
    guess: runGuess, outside: !!SESSION && basename(sessionDir) !== SESSION,
    agents: [...liveAgents.values()]
      .sort((x, y) => (Date.parse(x.startedAt || 0) || Infinity) - (Date.parse(y.startedAt || 0) || Infinity))
      .map(({ offset, matched, seen, ...a }) => a),
  };
}

server.listen(0, '127.0.0.1', () => {              // loopback only, never 0.0.0.0
  writeFileSync(portFile, JSON.stringify({ port: server.address().port, stateToken, scriptPath }));
});

// Deny by default on expiry. Never auto-approve. Cleared once a decision is taken.
const idleTimer = setTimeout(() => die(2), IDLE_MS).unref();
